### ISSUE TITLE
Compiling on Ubuntu

### ISSUE THREAD

**Issue by AndyPi** [maazl/vc4asm#12]
I tried to compile 0.2.2 on x64 PC 

`g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609` and got two errors.

First
`AssembleInst.cpp:45:41: error: ‘::isinf’ has not been declared
   if (fabs(value.fValue) > FLT_MAX && !(::isinf(value.fValue)))
                                         ^
AssembleInst.cpp:45:41: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from AssembleInst.cpp:17:
/usr/include/c++/5/cmath:621:5: note:   ‘std::isinf’
     isinf(_Tp __x)`

I took the tip and changed to std::isinf

Second
`AssembleInst.cpp:397:12: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
   if (!pm2 == pm)
`
I changed to if ( pm2 != pm ) but on reflection I think you wrote what you intended, how to avoid the messy warning though perhaps  if ( (!pm2)==pm )
 
This is great work !

regards
Andy

**Comment by ghost** [comment]
I have fixed both of those and have submitted a pull request.  

You can  checkout my fork in the meantime 

```
git clone https://github.com/maazl/vc4asm.git # you probably already did this
cd vc4asm
git fetch origin pull/17/head:Nom-DePlume-fixes
git checkout Nom-DePlume-fixes
cd src
make
```

**Comment by maazl** [comment]
Fix merged into master.
