### ISSUE TITLE
Cannot build with new Makefile on macOS

### ISSUE THREAD

**Issue by ilovezfs** [maazl/vc4asm#18]
Attempting to build V0.2.3 fails on macOS due to the changes made in https://github.com/maazl/vc4asm/pull/15. The old Makefile still builds successfully.

The error is, as follows:
```
==> make -C src
mkdir ../obj
g++ -Wall -std=c++11 -g -c -fPIC -o ../obj/utils.o utils.cpp
g++ -Wall -std=c++11 -g -c -fPIC -o ../obj/Message.o Message.cpp
g++ -Wall -std=c++11 -g -c -fPIC -o ../obj/expr.o expr.cpp
g++ -Wall -std=c++11 -g -c -fPIC -o ../obj/Inst.o Inst.cpp
g++ -Wall -std=c++11 -g -c -fPIC -o ../obj/Eval.o Eval.cpp
g++ -Wall -std=c++11 -g -c -fPIC -o ../obj/Validator.o Validator.cpp
g++ -Wall -std=c++11 -g -c -fPIC -o ../obj/AssembleInst.o AssembleInst.cpp
g++ -Wall -std=c++11 -g -c -fPIC -o ../obj/Parser.o Parser.cpp
g++ -Wall -std=c++11 -g -c -fPIC -o ../obj/vc4asm.o vc4asm.cpp
g++ -Wall -std=c++11 -g -c -fPIC -o ../obj/WriteELF.o WriteELF.cpp
gcc -Wall -std=c++11 -g  -o ../bin/vc4asm ../obj/utils.o ../obj/Message.o ../obj/expr.o ../obj/Inst.o ../obj/Eval.o ../obj/Validator.o ../obj/AssembleInst.o ../obj/Parser.o ../obj/vc4asm.o ../obj/WriteELF.o -lm -lstdc++
g++ -Wall -std=c++11 -g -c -fPIC -o ../obj/Disassembler.o Disassembler.cpp
g++ -Wall -std=c++11 -g -c -fPIC -o ../obj/vc4dis.o vc4dis.cpp
gcc -Wall -std=c++11 -g  -o ../bin/vc4dis ../obj/utils.o ../obj/Message.o ../obj/expr.o ../obj/Inst.o ../obj/Eval.o ../obj/Validator.o ../obj/Disassembler.o ../obj/vc4dis.o -lm -lstdc++
mkdir ../lib
ar rcs -o ../lib/libvc4asm.a ../obj/utils.o ../obj/Message.o ../obj/expr.o ../obj/Inst.o ../obj/Eval.o ../obj/Validator.o ../obj/AssembleInst.o ../obj/Parser.o ../obj/WriteELF.o ../obj/Disassembler.o
ar: illegal option combination for -r
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make: *** [../lib/libvc4asm.a] Error 1
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
```

**Comment by doe300** [comment]
Can you build successfully if you replace the `ar rcs ...` with `ar -r -cs ...` ?

**Comment by ilovezfs** [comment]
```
ar -r -cs -o ../lib/libvc4asm.a ../obj/utils.o ../obj/Message.o ../obj/expr.o ../obj/Inst.o ../obj/Eval.o ../obj/Validator.o ../obj/AssembleInst.o ../obj/Parser.o ../obj/WriteELF.o ../obj/Disassembler.o
ar: illegal option combination for -r
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make: *** [../lib/libvc4asm.a] Error 1
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
```

**Comment by ilovezfs** [comment]
If I also remove `-o`, the fun level goes way up: https://gist.github.com/ilovezfs/d9b3bba09a4fc8d71d8380f0c059303f

**Comment by doe300** [comment]
Strange, according to the mac man-pages for [ar](http://www.manpages.info/macosx/ar.1.html), these flags are all supported. And adding or removing the `-o` changes nothing in the output on my linux machine.

> Undefined symbols for architecture x86_64

This seems to point to a missing/wrong-version library. But since the undefined symbols are 

> std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::find(char, unsigned long) const

they should be provided in the standard library.

Possible fixes:
1) try replacing the `LD  = gcc` with `LD = g++` in the Makefile (line 6), see [here](http://stackoverflow.com/a/11975884)
2) Maybe you need to change the standard-library, the program is linked against, see [here](http://stackoverflow.com/a/19637199)

**Comment by ilovezfs** [comment]
As I mentioned, the old Makefile works, so not sure why we'd need to mess with the standard library.

**Comment by doe300** [comment]
Because I don't know any better way;)

Another attempt: Replace the `-shared` with `-dynamiclib` (Makefile, line 37), which seems to be the way to link shared libraries on mac OS, taken from [here](http://stackoverflow.com/a/14230346).

**Comment by ilovezfs** [comment]
@doe300 yes this works:
```
diff --git a/src/Makefile b/src/Makefile
index ddf56ff..19f058b 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -3,7 +3,7 @@ CPPFLAGS = -c -fPIC
 LDFLAGS  =
 LIBS     = -lm -lstdc++
 CC  = g++
-LD  = gcc
+LD  = g++
 AR	= ar
 EXE =
 O   = .o
@@ -31,7 +31,7 @@ clean:
 	$(LD) $(FLAGS) $(LDFLAGS) -o $@ $(DISOBJECTS) $(LIBS)
 	
 ../lib/libvc4asm.a : $(LIBOBJECTS) | ../lib
-	$(AR) rcs -o $@ $(LIBOBJECTS)
+	$(AR) rcs $@ $(LIBOBJECTS)
 	
 ../lib/libvc4asm.so : $(LIBOBJECTS) | ../lib
 	$(LD) -shared -o $@ $(LIBOBJECTS)
```

**Comment by ilovezfs** [comment]
Note there are still a couple porting issues with the Makefile, namely that the usual shared library extension on macOS is `.dylib` not `.so`, and that the dylib ID of the library is ending up as `../lib/libvc4asm.so` not `/usr/local/Cellar/vc4asm/0.2.3/lib/libvc4asm.so` (or `/usr/local/Cellar/vc4asm/0.2.3/lib/libvc4asm.dylib` if the extension is switched).

Note that Homebrew automatically fixes the latter issue
```
Changing dylib ID of /usr/local/Cellar/vc4asm/0.2.3/lib/libvc4asm.so
  from ../lib/libvc4asm.so
    to /usr/local/opt/vc4asm/lib/libvc4asm.so
```

Of course, I can just continue to only install the programs in `bin` and not install the libraries.

**Comment by ilovezfs** [comment]
(Usually it would be changing the dylib ID from `/usr/local/Cellar/vc4asm/0.2.3/lib/libvc4asm.so` to `/usr/local/opt/vc4asm/lib/libvc4asm.so` so it's basically an accident that it'll get set as expected because we always change it anyway (from the Cellar path to the opt path) but that would certainly not be the case for anyone building outside of Homebrew, and a dylib ID of `../lib/libvc4asm.so` would not really function properly.)

**Comment by doe300** [comment]
Seems like we need different built-targets for Linux and mac OS, which I have no idea how to do that with Makefiles.

Another idea that comes into my mind is to use CMake, which fixes the problem of correctly creating the correct version of library and maybe also fix the path-issue ...

**Comment by maazl** [comment]
I already use cmake, but this job has not yet completed so I did not publish the results. The samples and the test cases do no longer build correctly.
But I plan to use cmake for release 0.3.

**Comment by maazl** [comment]
The issue should be fixed in branch V2.x by doe300 and branch master by switching to cmake.
