### ISSUE TITLE
Strange mov instruction error

### ISSUE THREAD

**Issue by wallneradam** [maazl/vc4asm#23]
When compile this code:
`mov r0, 0x02020202`

The result will be:
`0x01010101, 0xe00049e0`
Disassembled:
`ldi r0, 0x1010101`

The strange thing is, this behaviour is only for power of 2s and only if bytes repeated 4 times in an integer:
0x02020202, 0x04040404, 0x08080808 ...

Workaround is using `ldi` instead `mov`, but I found using mov is much more intuitive.

**Comment by maazl** [comment]
Well, this was a tricky one.
vc4asm will normally load the constant 0x02020202 by the small immediate value 1.0/128.0 combined with MUL ALU pack, i.e. `mov _target_.8abcd, 7.8125E-3`. This keeps the ADD ALU free for another opcode.
But to save ALU power this instruction is converted back to `ldi` if no other opcode is packed into the same instruction word. At this point the behavior of the MUL ALU, i.e. the packing of a float value into an color value has to emulated. And this emulation caused rounding errors.
One bug less; THX
