### ISSUE TITLE
mov with packing breaks with 0

### ISSUE THREAD

**Issue by Seneral** [maazl/vc4asm#26]
Using mov together with packing signals breaks previously packed operations when a 0 is written.
For example:
```
mov ra10.8asi, 255;
mov ra10.8bsi, 0;
```
It doesn't matter what you write as the first value, it will always read 0 as well. Any nop; in between seem to have no effect either.
It affects the ALL previous packing operation on that pixel, not just the previous.

If you switch both statements, it works as expected, but that only is an option if you know the values beforehand (e.g. no macros).
If you replace mov with ldi, it works as expected, but without possible optimization as ALU instruction.
If you replace 0 with 1, it also works as expected, or add 1 to each macro, that works as well.
The following works, too, but only for small immediates:
```
mov ra10, 0; 
add ra10.8asi, ra10.8asi, 15; 
add ra10.8bsi, ra10.8bsi, 0;
```

So it's not critical, depending on what you want there are lots of workarounds.
If you need a test set up (printing to framebuffer to visualize) I can provide that.

What I assume the error is: If the compiler sees a mov with any 0 input, it will immediately optimize the packing operation away and write 0 to the whole pixel.

**Comment by maazl** [comment]
Am 19.03.20 um 17:15 schrieb Levin G.:
> Using mov together with packing signals breaks previously packed 
> operations when a 0 is written.
> For example:
> 
> |mov ra10.8asi, 255; mov ra10.8bsi, 0; |
> 
> It doesn't matter what you write as the first value, it will always read 
> 0 as well. Any nop; in between seem to have no effect either.
> It affects the ALL previous packing operation on that pixel, not just 
> the previous.

The first instruction works just fine. It is assembled as
   shr ra10.8asi, -8, -8
into the ADD ALU.

However, pack modes on mov xxx.pack, x do not work for small immediate 
values. The pack mode is discarded and so the entire register is 
overwritten.

Fixed at github master.


Marcel

**Comment by Seneral** [comment]
Thank you so much for your fast fix! Worked wonderfully.
