### ISSUE TITLE
Nested rep->if->rep causes if to be unterminated

### ISSUE THREAD

**Issue by Seneral** [maazl/vc4asm#31]
Another minor issue with the preprocessor, the following code will result in the error
`Warning P145.20: .if at line 2 in current file unterminated.`

```
.rep x, 2
    .if 1
        .rep y, 2
            nop;
        .endr
    .endif
.endr 
```
If you remove any of the nests, it works fine again.

**Comment by maazl** [comment]
Works for me.
I added a test case that passed without any changes.

**Comment by Seneral** [comment]
Terribly sorry, was still on an older version...
