### ISSUE TITLE
Website has invalid HTTPS certificate

### ISSUE THREAD

**Issue by Seneral** [maazl/vc4asm#32]
This has been the case for a couple months now as far as I am aware, which is sad to see since it has a bunch of good documentation.
Luckily it is still on the wayback machine.
Do you have any plans on bringing it back?
I'm in the process of releasing a thesis and the implementation uses vc4asm (seriously, thank you) and so I would like to cite it, the website or the github repo, doesn't matter.

**Comment by maazl** [comment]
The website isn't down and it has not been down in the last months (except for short maintenance maybe).
I can only guess that it is blocked for you. Maybe you activated HTTPS only mode. This site does not use HTTPS since it has only public content anyway. It also has no IPV6 address if this matters.

**Comment by Seneral** [comment]
Yeah I should have checked on mobile, no problem there.
And it was the https issue, however the page behaviour was not as expected.
It seems there is a security certificate for https://maazl.de/, but it is expired or wrong, and the web page is simply:
"Bitte kommen Sie später wieder. Die Webseite wird gerade bearbeitet. "

On browsers that have no preference of https at all, e.g. Chrome, visiting http://maazl.de/ works fine, if you load the https page it will show the maintenance page. Easy fix, no behaviour that keeps you from switching.

On Chromium (probably because of default security settings, haven't dug too far into it) it depends on what page you load first. If you load the https site (happened to me because I copied from firefox) then it will from now on know that it exists and use it, so no way for you to visit the http site even if you remove the s - the only way for you to visit it on Chromium after you visited the http site is to clear your browser data, then it will allow you to load the http site.

On Firefox the behaviour was pretty similar to Chromium, for some reason it loaded the https site for me initially and I could not figure out how to force it to use the http site. Disabling https-only mode per-site wasn't enough, it would still refuse to load the http site and switch to the https maintenance site - I assume since it knew it was there. You have to either disable https-only mode browser-wide or reset your browser data to access http://maazl.de/. After a reset I was able to properly visit the http site directly. I'm not sure what caused me to get stuck in the state that no matter what, I couldn't visit the http site.

So yeah. Browser issue, but I would still advise you to either remove the https part (it has an expired certificate from GeoTrust Inc from 14. November 2018) as that seems to confuse the browsers thinking it is the same site.

**Comment by Seneral** [comment]
Found this again, just to be clear, I still cannot access the site in my main browser (firefox) unless I explicitly disable https-only browser-wide for the duration of the access, which is not optimal. This is the only site I ever had issues on (besides those geolocking the EU because of GDPR).

**Comment by maazl** [comment]
A new provider server fixed the problem
