### ISSUE TITLE
Add a license (to asm include files)

### ISSUE THREAD

**Issue by Seneral** [maazl/vc4asm#33]
I am using the file "vc4.inc" in my project, but without a license, I am technically not allowed to include it at all, which I only thought of now. I think at least the include files, that are expected to be included in other projects, deserve a license, if not the whole assembler. Also, if possible, one that isn't GPL, as that would infect any project using it (and would prevent me from using it, too, as I am using the MPL license).
Thank you for considering!

**Comment by maazl** [comment]
I would prefer GPLv3, but of course with a runtime exception. So include files, C templates and possible future runtime libraries are LGPL. This should be compatible to MPL and commercial use too.

**Comment by Seneral** [comment]
Yep GPL does make sense for it, if you can explicitly exclude the "share" folder and give that a more permissive license (just in words might suffice? Not sure). Thanks!
