### ISSUE TITLE
Unary operators ceil() and floor() don't take floating point operands

### ISSUE THREAD

**Issue by LoekHabets** [maazl/vc4asm#34]
Hello maazl,

It seems there is a bug with `ceil` and `floor` that makes it impossible to convert float constants to integers. See the following example, where we try to multiply a value by a power of 2 that normally doesn't fit in the small immediate field.

example.qasm:
```
.set vec_size, 16
shl r0, elem_num, floor(log2(vec_size))
```
yields:
```
example.qasm (2,39): ERROR E10.1: Cannot apply unary operator ceil to operand of type floating point.
FATAL a250: Aborted because of earlier errors.
```

This bug makes it difficult to use bit shifts in place of multiplication (or worse, division) in situations where numbers need to be manipulated by powers of 2.

Kind regards,
Loek

**Comment by maazl** [comment]
Should work in master branch now

**Comment by LoekHabets** [comment]
Thanks for fixing this so quickly!
